Add ISOBUS Guidance (Steering) Interface
ad3154/Isobus-plus-plus pull request #252
Opened 2023-05-11 01:38 UTC by ad3154

## What's new

* Added interface for sending and receiving guidance messages.

This PR defines an interface for sending and receiving ISOBUS guidance messages.
These messages are used to steer ISOBUS compliant machines, steering valves, and implements in general.

### Important notes

**Please use extreme care if you try to steer a machine with this interface!** Remember that this library is licensed under The MIT License, and that by obtaining a copy of this library and of course by attempting to steer a machine with it, you are agreeing to our license.

These messages are expected to be deprecated or at least made redundant in favor of Tractor Implement Management (TIM) at some point by the AEF, though the timeline on that is not known at the time of writing this, and it's likely that many machines will continue to support this interface going forward due to its simplicity over TIM. At the time of writing, these messages are widely used and supported.

2023-05-11 07:42 UTC, GwnDaan commented
Cool stuff! Were you able to test this in practice? I'm curious to see the results :) if not, I can try to do some testing and perhaps add an example to the codebase?

2023-05-11 14:12 UTC, ad3154 commented
> Cool stuff! Were you able to test this in practice? I'm curious to see the results :) if not, I can try to do some testing and perhaps add an example to the codebase?

Thanks! This one I don't have a practical way to test, so if you have a device that accepts this message I would certainly appreciate help testing it. This definitely feels like one we'd want to add an example and tutorial page for if we can get it working on some actual machine.

I think this is probably only one piece of a larger puzzle in practice though, because if you wanted to develop a complete guidance controller, you'd probably also need the speed/odometry messages, the standard ISOBUS heartbeat message, and maybe other ones depending on what is being steered. Little by little we're getting there though, haha.

2023-05-11 14:20 UTC, ad3154 commented
I will also note that it might be tricky to know how exactly to integrate it with a particular platform, as some steering controllers have arcane limitations, such as:

- Some don't accept the guidance curvature command as a broadcast, only point to point (which is fine, I suppose...)
- Some don't allow multiple senders of the message, so you might need to adjust settings within the steering controller for it to listen to you, or you might need to impersonate the platform's guidance controller
- Some might require both messages to be present (because it might use the remote engage signal, for example)

And maybe other things... tough to know.

2023-05-13 19:17 UTC, GwnDaan requested changes
Hi! I got to testing on a Fendt 500 S4, which I initially thought would support this interface. But I'm currently not sure? It sends the Guidance Machine Info message every 100ms, but the built in steering system doesn't send the Guidance System Command. Therefore I assume the guidance system is not handled via isobus, but one of the other internal busses instead, and only ouput as readonly over isobus.

Nevertheless I successfully got the GuidanceMachineInfo command coming in, and was able to read it out! So I'd call that a success 😄. Only the `estimated_curvature` had meaningful values, the others were set to unsupported/unavailable. Though that probably is on the tractor side.

What are your thoughts? Is it worth to try to send the GuidanceSystemCommand? Or do you recon it will just not work? 

I had a few comment I stumbled across when testing it in practice. And some small nit-worthy changes I made on a forked branch, which I'll make a PR for.

Again, really cool stuff, I really like where this all is heading!

2023-05-13 22:51 UTC, ad3154 commented on isobus/include/isobus/isobus/isobus_guidance_interface.hpp
Yeah, I even included the event dispatcher header file meaning to do that and just forgot, good catch.

2023-05-13 22:53 UTC, ad3154 commented
> Hi! I got to testing on a Fendt 500 S4, which I initially thought would support this interface. But I'm currently not sure? 

It probably does TIM instead then... AGCO (which owns Fendt) was the original creator of TIM 😣

2023-05-14 15:11 UTC, GwnDaan commented
> > Hi! I got to testing on a Fendt 500 S4, which I initially thought would support this interface. But I'm currently not sure?
> 
> It probably does TIM instead then... AGCO (which owns Fendt) was the original creator of TIM 😣 (I'm pretty sure at least)

Yea... I'll have access to some other tractors with guidance in a month or so. Then I can probably do some testing with the guidance system command, only if they happen to support it obviously. Once the dispatcher system is implemented, I'll for now add the example that does read-only stuff as a starting point. Which we can later complete with the steering part when tested, and if desired

2023-05-14 15:29 UTC, ad3154 commented
I've added your suggestions such as events, and fixed the missing timeout checking 🙂

2023-05-16 13:05 UTC, GwnDaan approved these changes

2023-05-16 15:30 UTC, merged